import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Header from '@/widgets/Header';
import Footer from '@/widgets/Footer';

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata: Metadata = {
	title: 'Двери \u2013 Входные и межкомнатные',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Header />
				<div className="min-h-96 bg-gray-100 pb-14">{children}</div>
				<div className="bg-gray-900 text-gray-100">
					<Footer />
				</div>
			</body>
		</html>
	);
}
