name: Pull requests check

on:
   pull_request:

jobs:
   lint:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - name: install pnpm
           uses: pnpm/action-setup@v4
           with:
              version: 10
         - uses: actions/setup-node@v3
           with:
              node-version: 20.x.x
              cache: pnpm

         - name: Install dependencies
           run: pnpm install --frozen-lockfile

         - name: Linting
           run: pnpm lint

         - name: Linting types
           run: pnpm lint:types

         - name: Testing
           run: pnpm test
